# Experiment Configuration Descriptor

# The following sections are required: 
# experiment, collection-reader, pipeline and post-process

# Each resource should be specified either as:
#  inherit or class:

# -inherit- will look for a file WITHIN the classpath 
# on the directory specified by the doted syntax 
#  a.b.c => a/b/c 
# inherited properties can be overridden directly 
# on the body of the declaration

# -class- will look for a class on the classpath, and is 
# intended as a shortcut for classes that might not have 
# default configuration parameters

# When the attributes are specified as a resource
# to be loaded by an annotator, they should be specified 
# as a string using the multiline syntax |\n [class|inherit]: fully.qualified.resource

# A pipeline is typically defined by phases that inherit
# from base.phase, this element provides all the book keeping 
# functionality for experimentation.
# Elements that need to collect information form the different
# experiment options can be specified at the end of the pipeline.

# Besides these elements, any AnalysisEngine or CasConsumer 
# can be added to the pipeline in a similar way. 

# Some options within a phase can have combinatorial options
# for a detailed example see: example.third-phase-annotator

# A final note on YAML syntax, indentation is relevant to
# determine nesting of elements and some characters 
# are reserved (-,:) so use quotes "" to use them on strings

experiment:
  name: example-experiment
  author: elmerg

persistence-provider:
  inherit: db.local-persistence-provider
  
configuration:
  inherit: db.cse-broker-config

collection-reader:
  inherit: db.local-collection-reader
  dataset: TREC11
  named-subset: SMALL_TREC11
  
stages:
  - stage:
    pipeline:
      - inherit: cse.phase 
        name: first-phase
        options: |
          - inherit: example.first-phase-annotator-a
          - class: edu.cmu.lti.oaqa.cse.example.FirstPhaseAnnotatorB1 
          - pipeline: [class: edu.cmu.lti.oaqa.cse.example.FirstPhaseAnnotatorB1, inherit: example.first-phase-annotator-a]  
      
      - inherit: cse.phase 
        name: second-phase  
        options: |
          - class: edu.cmu.lti.oaqa.cse.example.SecondPhaseAnnotatorA1
          - class: edu.cmu.lti.oaqa.cse.example.SecondPhaseAnnotatorB1
          - class: edu.cmu.lti.oaqa.cse.example.SecondPhaseAnnotatorC1
      
      - inherit: eval.base-retrieval-aggregator
        scope: STAGE 
        
    post-process: 
      - inherit: eval.retrieval-measures-evaluator
      - inherit: report.csv-report-generator
        builders: |
          - inherit: report.f-measure-report-component  
      - inherit: funnel.funnel-consumer
        experiment-listeners: |       
          - inherit: funnel.retrieval-measures-00-map-threshold
    
  - stage:
    pipeline:
      - inherit: cse.phase  
        name: third-phase  
        options: |
          - inherit: example.third-phase-annotator
      
      - inherit: eval.base-retrieval-aggregator
      
      - inherit: eval.trace-consumer
        listeners: |
          - inherit: test.eval.example-consumer

    post-process: 
      - inherit: eval.retrieval-measures-evaluator
      - inherit: report.csv-report-generator
        builders: |
          - inherit: report.f-measure-report-component
